//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formulario_102A
{
    using System;
    using System.Collections.Generic;
    
    public partial class formulario_104
    {
        public int id_Formulario { get; set; }
        public string Ruc_Usuario { get; set; }
        public string periodo { get; set; }
        public Nullable<double> c401 { get; set; }
        public Nullable<double> c409 { get; set; }
        public Nullable<double> c411 { get; set; }
        public Nullable<double> c419 { get; set; }
        public Nullable<double> c421 { get; set; }
        public Nullable<double> c429 { get; set; }
        public Nullable<double> c499 { get; set; }
        public Nullable<double> r601 { get; set; }
        public Nullable<double> r605 { get; set; }
        public Nullable<double> r608 { get; set; }
        public Nullable<double> r609 { get; set; }
        public Nullable<double> r615 { get; set; }
        public Nullable<double> r620 { get; set; }
        public Nullable<double> r699 { get; set; }
    }
}
