//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Formulario_102A
{
    using System;
    using System.Collections.Generic;
    
    public partial class formulario_102A
    {
        public int id_Formulario { get; set; }
        public Nullable<int> id_Usuario { get; set; }
        public string periodo { get; set; }
        public Nullable<int> NoEmpleados { get; set; }
        public Nullable<int> i481 { get; set; }
        public Nullable<int> i718 { get; set; }
        public Nullable<int> i729 { get; set; }
        public Nullable<int> i741 { get; set; }
        public Nullable<int> g491 { get; set; }
        public Nullable<int> g739 { get; set; }
        public Nullable<int> g751 { get; set; }
        public Nullable<int> r749 { get; set; }
        public Nullable<int> r759 { get; set; }
        public Nullable<int> r769 { get; set; }
        public string b740 { get; set; }
        public Nullable<int> p768 { get; set; }
        public Nullable<int> p771 { get; set; }
        public Nullable<int> p772 { get; set; }
        public Nullable<int> p773 { get; set; }
        public Nullable<int> p774 { get; set; }
        public Nullable<int> p775 { get; set; }
        public Nullable<int> p779 { get; set; }
        public Nullable<int> p780 { get; set; }
        public Nullable<int> c832 { get; set; }
        public Nullable<double> c839 { get; set; }
        public Nullable<int> c840 { get; set; }
        public Nullable<int> c845 { get; set; }
        public Nullable<int> c846 { get; set; }
        public Nullable<double> c855 { get; set; }
        public Nullable<double> c856 { get; set; }
        public Nullable<double> c859 { get; set; }
        public Nullable<double> c869 { get; set; }
    
        public virtual Usuarios Usuarios { get; set; }
    }
}
